### ISSUE TITLE
Load balancer ARP responder broken since 21.06

### ISSUE THREAD

**Issue by tomponline** [ovn-org/ovn#124]
The [LXD](https://github.com/lxc/lxd) team use OVN load balancers for its Network forward functionality (https://linuxcontainers.org/lxd/docs/master/howto/network_forwards/).

We have had a [user report](https://discuss.linuxcontainers.org/t/cant-make-network-forward-working-in-cluster-environment/13579) (since confirmed) from @lepokle that recent versions of OVN have broken the ARP responder functionality of OVN load balancers.

@lepokle has identified that it appears to broken since 21.06 specifically the commit https://github.com/ovn-org/ovn/commit/ea6ee901ff9107a084bc830a8a38c4e0bd9f75f7

We no longer see the OVN logical router responding to ARP requests for the load balancer listen IP on the chassis's gateway port.
If packets are manually routed to the OVN logical router's gateway port IP then the load balancer does still work though, so its just the ARP responder that has been broken.

On a pre-21.06 OVN version we see the following logical flows configured with a load balancer:

```
# ovn-nbctl --version                                                                                               
ovn-nbctl 21.03.0
Open vSwitch Library 2.15.90
DB Schema 5.31.0

# ovn-sbctl list logical_flow | grep bbb.76.20.84                                                                   
match               : "ct.est && ip && ip4.dst == bbb.76.20.84 && is_chassis_resident(\"cr-lxd-net11-lr-lrp-ext\")"
actions             : "eth.dst = eth.src; eth.src = xreg0[0..47]; arp.op = 2; /* ARP reply */ arp.tha = arp.sha; arp.sha = xreg0[0..47]; arp.tpa = arp.spa; arp.spa = bbb.76.20.84; outport = inport; flags.loopback = 1; output;"
match               : "inport == \"lxd-net11-lr-lrp-int\" && arp.op == 1 && arp.tpa == bbb.76.20.84"
match               : "ip && ip4.dst == bbb.76.20.84"
actions             : "reg1 = bbb.76.20.84; ct_lb(backends=10.161.64.2);"
match               : "ct.new && ip4.dst == bbb.76.20.84"
match               : "ct.new && ip && ip4.dst == bbb.76.20.84 && is_chassis_resident(\"cr-lxd-net11-lr-lrp-ext\")"
actions             : "eth.dst = eth.src; eth.src = xreg0[0..47]; arp.op = 2; /* ARP reply */ arp.tha = arp.sha; arp.sha = xreg0[0..47]; arp.tpa = arp.spa; arp.spa = bbb.76.20.84; outport = inport; flags.loopback = 1; output;"
match               : "inport == \"lxd-net11-lr-lrp-ext\" && arp.op == 1 && arp.tpa == bbb.76.20.84 && is_chassis_resident(\"cr-lxd-net11-lr-lrp-ext\")"
```

Specifically there is a mention of an `/* ARP reply */` flow.

However in later versions we see the ARP reply flow is gone:

```
# ovn-nbctl --version
ovn-nbctl 21.06.0
Open vSwitch Library 2.15.90
DB Schema 5.32.0

# ovn-sbctl list logical_flow | grep bbb.76.20.84                                                                   
match               : "ct.est && ip && ip4.dst == bbb.76.20.84 && is_chassis_resident(\"cr-lxd-net11-lr-lrp-ext\")"
match               : "ip && ip4.dst == bbb.76.20.84"
match               : "inport == \"lxd-net11-lr-lrp-int\" && arp.op == 1 && arp.tpa == { bbb.76.20.84 }"
actions             : "reg1 = bbb.76.20.84; ct_lb(backends=10.161.64.2);"
match               : "ct.new && ip4.dst == bbb.76.20.84"
match               : "inport == \"lxd-net11-lr-lrp-ext\" && arp.op == 1 && arp.tpa == { bbb.76.20.84 } && is_chassis_resident(\"cr-lxd-net11-lr-lrp-ext\")"
match               : "ct.new && ip && ip4.dst == bbb.76.20.84 && is_chassis_resident(\"cr-lxd-net11-lr-lrp-ext\")"
```

**Comment by tomponline** [comment]
To give a bit more info on this, we are expecting the OVN logical router to respond to ARP requests for the load balancer's listen IP that is outside of the router's own subnets.

**Comment by tomponline** [comment]
I am still experiencing the issue on 22.03.0 (despite it having a commit that seems like it would fix it https://github.com/ovn-org/ovn/commit/ecc941c70f1675b66f6ecb2cdf09df362f62c97a):

```
ovn-nbctl --version
ovn-nbctl 22.03.0
Open vSwitch Library 2.17.0
DB Schema 6.1.0
```

**Comment by tomponline** [comment]
Reproducer steps:

```
lxc launch images:ubuntu/jammy v1 --vm
lxc shell v1
  apt install snapd ovn-host ovn-central -y
  snap install lxd --edge
  lxd init --auto
  sudo ovs-vsctl set open_vswitch . \
    external_ids:ovn-remote=unix:/var/run/ovn/ovnsb_db.sock \
    external_ids:ovn-encap-type=geneve \
    external_ids:ovn-encap-ip=127.0.0.1
    
  lxc network show lxdbr0
  config:
    ipv4.address: 10.254.169.1/24
    ipv4.nat: "true"
    ipv6.address: fd42:41fc:e9fc:6418::1/64
    ipv6.nat: "true"
  description: ""
  name: lxdbr0
  type: bridge
  
  lxc network set lxdbr0 \
    ipv4.dhcp.ranges=10.254.169.2-10.254.169.10 \
    ipv4.ovn.ranges=10.254.169.11-10.254.169.20 \
    ipv4.routes=192.0.2.1/32

  lxc network create ovn1 --type=ovn network=lxdbr0
  lxc launch images:alpine/3.15 c1 -n ovn1
  lxc ls
  +------+---------+--------------------+-----------------------------------------------+-----------+-----------+
  | NAME |  STATE  |        IPV4        |                     IPV6                      |   TYPE    | SNAPSHOTS |
  +------+---------+--------------------+-----------------------------------------------+-----------+-----------+
  | c1   | RUNNING | 10.12.242.2 (eth0) | fd42:8f11:9df0:efd1:216:3eff:fe10:125a (eth0) | CONTAINER | 0         |
  +------+---------+--------------------+-----------------------------------------------+-----------+-----------+
  
  lxc network forward create ovn1 192.0.2.1 target_address=10.12.242.2

  ping 192.0.2.1
  PING 192.0.2.1 (192.0.2.1) 56(84) bytes of data.
  64 bytes from 192.0.2.1: icmp_seq=1 ttl=63 time=1956 ms
  64 bytes from 192.0.2.1: icmp_seq=2 ttl=63 time=941 ms
  64 bytes from 192.0.2.1: icmp_seq=3 ttl=63 time=0.423 ms
  64 bytes from 192.0.2.1: icmp_seq=4 ttl=63 time=0.212 ms
  64 bytes from 192.0.2.1: icmp_seq=5 ttl=63 time=0.236 ms
  64 bytes from 192.0.2.1: icmp_seq=6 ttl=63 time=0.233 ms
  64 bytes from 192.0.2.1: icmp_seq=7 ttl=63 time=0.213 ms
  64 bytes from 192.0.2.1: icmp_seq=8 ttl=63 time=0.202 ms
  64 bytes from 192.0.2.1: icmp_seq=9 ttl=63 time=0.242 ms
  64 bytes from 192.0.2.1: icmp_seq=10 ttl=63 time=0.247 ms
  From 10.254.169.1 icmp_seq=11 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=12 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=13 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=14 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=15 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=16 Destination Host Unreachable
  64 bytes from 192.0.2.1: icmp_seq=17 ttl=63 time=1625 ms
  64 bytes from 192.0.2.1: icmp_seq=18 ttl=63 time=601 ms
  64 bytes from 192.0.2.1: icmp_seq=19 ttl=63 time=0.263 ms
  64 bytes from 192.0.2.1: icmp_seq=20 ttl=63 time=0.071 ms
  64 bytes from 192.0.2.1: icmp_seq=21 ttl=63 time=0.262 ms
  64 bytes from 192.0.2.1: icmp_seq=22 ttl=63 time=0.204 ms
  64 bytes from 192.0.2.1: icmp_seq=23 ttl=63 time=0.140 ms
  64 bytes from 192.0.2.1: icmp_seq=24 ttl=63 time=0.198 ms
  64 bytes from 192.0.2.1: icmp_seq=25 ttl=63 time=0.226 ms
  64 bytes from 192.0.2.1: icmp_seq=26 ttl=63 time=0.218 ms
  From 10.254.169.1 icmp_seq=27 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=28 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=29 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=30 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=31 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=32 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=33 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=34 Destination Host Unreachable
  From 10.254.169.1 icmp_seq=35 Destination Host Unreachable
```

**Comment by numansiddique** [comment]
Thanks for reporting the issue.

I'll check the issue in more detail and come back to you.

**Comment by tomponline** [comment]
> Thanks for reporting the issue.
> 
> I'll check the issue in more detail and come back to you.

Thanks! :) Let me know if you need any more info.

**Comment by numansiddique** [comment]
Is it possible to share the OVN NB DB and SB DB ?

**Comment by numansiddique** [comment]
@tomponline  this commit https://github.com/ovn-org/ovn/commit/5c4010dd7f41d2ebd7b8aa4f0350ee7c803b94a5 removed ARP responder flows for load balancer vips which are not reachable from the router.

@dceara   wdyt about this reported issue ?  We should add back this support with an option to enable it if CMS desires ?

**Comment by tomponline** [comment]
Putting it under a feature flag  would be good.

**Comment by dceara** [comment]
@tomponline What do you think of a new `NB.Load_Balancer.options:arp_responder=<all|reachable>` with a default of `reachable`?  That would mean that the CMS would have to explicitly set it to `all` for each load balancer if it's desired that OVN generate ARP responder for all IPs.

Alternatively, we could add a new config option on the routers, e.g.: `NB.Logical_Router.options:lb_arp_responder=<all|reachable>` with a default of `reachable`.  This latter option has the advantage that a load balancer may be applied in different ways on different routers.  I'm not sure how important this extra flexibility is though.

**Comment by tomponline** [comment]
> 

Thanks for looking at this.

I think I would prefer the `NB.Load_Balancer.options:arp_responder` option as it then means its a property of the load balancer.
We don't tend to share load balancers between routers so the latter option wouldn't provide us any benefit.

Whilst we on the subject, I haven't checked, but did the change also prevent IPv6 NDP responders from working in the same way that IPv4 ARP responders were stopped? 

If not, then they probably should be for consistency, and then perhaps instead of `NB.Load_Balancer.options:arp_responder` th new option should be called `NB.Load_Balancer.options:neighbour_responder` to accommodate both IPv4 and IPv6 responders?

**Comment by dceara** [comment]
> > 
> 
> Thanks for looking at this.
> 
> I think I would prefer the `NB.Load_Balancer.options:arp_responder` option as it then means its a property of the load balancer. We don't tend to share load balancers between routers so the latter option wouldn't provide us any benefit.
> 

Makes sense.  I know ovn-kubernetes shares load balancers across routers but I don't see why they would need different behavior for the same load balancer.

> Whilst we are on the subject, I haven't checked, but did the change also prevent IPv6 NDP responders from working in the same way that IPv4 ARP responders were stopped?
> 

Yes.

> If not, then they probably should be for consistency, and then perhaps instead of `NB.Load_Balancer.options:arp_responder` th new option should be called `NB.Load_Balancer.options:neighbour_responder` to accommodate both IPv4 and IPv6 responders?

Good point, will do.  I just need to figure out if it should be "neighbour" or "neighbor" :).  We have both in the code base but we mostly use "neighbor" from what I can tell.

**Comment by simondeziel** [comment]
> Good point, will do. I just need to figure out if it should be "neighbour" or "neighbor" :). We have both in the code base but we mostly use "neighbor" from what I can tell.

ARP is an acronym so using NDP would make sense to me (`NB.Load_Balancer.options:ndp_responder`).

**Comment by tomponline** [comment]
Except NDP is an IPv6 protocol so one may assume that it would control IPV6 NDP only, so using the word "neighbour" (or "neighbor") would seem to cover both ARP and NDP.

**Comment by tomponline** [comment]
This way we would have one config option that enables both ARP and NDP responders.

**Comment by simondeziel** [comment]
Ah I misunderstood your proposal of a single config option, I like it better!

**Comment by dceara** [comment]
I sent a patch to implement this:
https://patchwork.ozlabs.org/project/ovn/list/?series=297414&state=*
https://mail.openvswitch.org/pipermail/ovs-dev/2022-April/393627.html

@tomponline It would be great if you could try it out and confirm it works for your case. Thanks!

**Comment by lepokle** [comment]
Hi @dceara,
thank you very much for your patch! I've just tried it out in our environment and it works perfectly! Thank you very much!
@tomponline
I've configured as suggested in patch via ovn-nbctl. Is there any chance that this option will be overwritten by LXD?

Thanks!

**Comment by tomponline** [comment]
@lepokle ah excellent glad you were able to test.

At the current time lxd will not override it.
We may add a feature setting in the future though that controls this flag, although I suspect we would leave it disabled by default for performance reasons.

**Comment by lepokle** [comment]
Any chance that this will be merged @dceara ?

**Comment by dceara** [comment]
@lepokle Sorry, I forgot to update this issue but the patch was merged a while ago: https://github.com/ovn-org/ovn/commit/7644698a783aef883a12ed74becec1dadedbf77a It's available in versions 22.06, 22.09 and 22.12.

**Comment by lepokle** [comment]
Hi @dceara ,
thank you very much, I'll test it with 22.12!!

**Comment by lepokle** [comment]
Hi @dceara ,
since 22.12 is not officially tagged, I've used now 22.09. I get the following error when starting ovn-controller:
`ovs|00035|physical|ERR|No tunnel endpoint found for HA chassis in HA chassis group of port cr-lxd-net5-lr-lrp-ext`
Could this be related to the new version?

**Comment by dceara** [comment]
> Hi @dceara , since 22.12 is not officially tagged, I've used now 22.09. I get the following error when starting ovn-controller: `ovs|00035|physical|ERR|No tunnel endpoint found for HA chassis in HA chassis group of port cr-lxd-net5-lr-lrp-ext` Could this be related to the new version?

Hmm, 22.12 is  tagged for a while: https://github.com/ovn-org/ovn/releases/tag/v22.12.0

I'm not sure about the error. There were some changes that were made in that area but it's hard to tell without looking at databases.
