### ISSUE TITLE
Build failure on Alpine Linux: too few arguments to function 'inet_parse_active'

### ISSUE THREAD

**Issue by rnalrd** [ovn-org/ovn#128]
Trying to build a release tarball (22.03.0) on Alpine Linux which uses musl libc instead of GLIBC and building stops with this error:

```
utilities/ovn-trace.c: In function 'parse_lb_option':
utilities/ovn-trace.c:217:10: error: too few arguments to function 'inet_parse_active'
  217 |     if (!inet_parse_active(s, 0, &ss, false)) {
      |          ^~~~~~~~~~~~~~~~~
In file included from /home/larena/alpine_build/shared/home/larena/aports/testing/ovn/src/openvswitch-2.13.7/lib/stream.h:25,
                 from utilities/ovn-trace.c:46:
/home/larena/alpine_build/shared/home/larena/aports/testing/ovn/src/openvswitch-2.13.7/lib/socket-util.h:51:6: note: declared here
   51 | bool inet_parse_active(const char *target, int default_port,
      |      ^~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:2309: utilities/ovn-trace.o] Error 1
```

You can build the attached Dockerfile to recreate the issue.

Expected result: being able to build OVN on Alpine Linux.

[Dockerfile.txt](https://github.com/ovn-org/ovn/files/8489715/Dockerfile.txt)

**Comment by numansiddique** [comment]
Please use OVS for building OVN from the submodule.
----
git submodule init ovs
git submodule update ovs
----

Latest OVS commit changed the signature of this function inet_parse_active().

**Comment by rnalrd** [comment]
Thank you, I've built it against the correct revision and this error is gone.
