### ISSUE TITLE
CI: why do you run sanitizers tests separately?

### ISSUE THREAD

**Issue by fsb4000** [ovn-org/ovn#137]
Hello 👋. I'm wonder why do you choose to run tests twice instead of combine sanitizers?
As far as I know ASAN + UBSAN +  LEAKSAN can be used together. It could save some CI time...

https://github.com/ovn-org/ovn/blob/a2748171f36a77b3ac1d7725c141fd56e529bff6/.github/workflows/test.yml#L42-L47

**Comment by dceara** [comment]
@fsb4000 If we don't lose any checks then that's ideal, yes!  Would you like to prepare a patch/open a PR?

**Comment by fsb4000** [comment]
Yes, I will.

**Comment by fsb4000** [comment]
Fixed by https://github.com/ovn-org/ovn/commit/5ea3c71f1e47d39936fe91267cbb206c15245a18
