### ISSUE TITLE
Investigate and fix `linux gcc system-test`

### ISSUE THREAD

**Issue by fsb4000** [ovn-org/ovn#143]
`linux gcc system-test` fail sometimes.
The test itself needs to be fixed, or the ovn code.
```
117: IPv6 prefix delegation -- ovn-northd -- parallelization=yes -- ovn_monitor_all=yes FAILED (ovs-macros.at:255)
118: IPv6 prefix delegation -- ovn-northd -- parallelization=yes -- ovn_monitor_all=no FAILED (ovs-macros.at:255)
119: IPv6 prefix delegation -- ovn-northd -- parallelization=no -- ovn_monitor_all=yes FAILED (ovs-macros.at:255)
120: IPv6 prefix delegation -- ovn-northd -- parallelization=no -- ovn_monitor_all=no FAILED (ovs-macros.at:255)
```

**Comment by almusil** [comment]
Hi, the patches are merged, could you please close this one as I don't have the required permission. 

Thanks.

**Comment by fsb4000** [comment]
Yes, I saw the patches https://github.com/ovn-org/ovn/commit/5175a198132e59a060efd16ea81178764f269efa and https://github.com/ovn-org/ovn/commit/b340d5d3af352ea4ece64b93e2bd59396586c217
Congrats 🎉 !
