### ISSUE TITLE
Does OVN snat only used to   external provider network ?

### ISSUE THREAD

**Issue by ruoniao** [ovn-org/ovn#158]
Could I use  lr-nat-add command to snated "logical ip" to "external ip" that tenant created privited "Logical_Switch_Port IP"?
I try used this but failed. Thanks for reading.

**Comment by numansiddique** [comment]
If a logical router has NAT (SNAT/DNAT) configured, then those nat rules are configured only if the logical router has a logical router port with gateway_chassis configured (ovn-nbctl lrp-set-gateway-chassis) or if the logical router is a gateway router (i.e  ovn-nbctl set logical_router lr0 options:chassis=<chassis_name>).

**Comment by ruoniao** [comment]
Thank you. I tested it with this command no problem.This Issue will be closed.
