### ISSUE TITLE
Is there alternative way to set dnat as previous `([ovn-nbctl lr-nat-add lr0 dnat 30.0.0.1:80 192.168.1.2:8080]`

### ISSUE THREAD

**Issue by bobz965** [ovn-org/ovn#162]
([ovn-nbctl lr-nat-add lr0 dnat 30.0.0.1:80 192.168.1.2:8080]

https://lists.linuxfoundation.org/pipermail/ovs-dev/2016-October/081124.html

**Comment by putnopvut** [comment]
NAT only works at L3, so you cannot specify ports for the external or logical address. If you want to translate L4 ports, then you will need to set up a load balancer on the router instead.
````
ovn-nbctl lb-add lb0 30.0.0.1:80 192.168.1.2:8080 tcp
ovn-nbctl lr-lb-add lr0 lb0
````
