### ISSUE TITLE
Could I use different versions of ovs during the compile and install of ovn

### ISSUE THREAD

**Issue by HanGuangyu** [ovn-org/ovn#165]
Could I use a different version of ovs during the compile and actual installation phases of ovn? Or I must use same version of ovs during the compile and install of ovn?

I want to compile ovn 20.06.3, but ovs  2.13.9 not compatible (such as ovn 20.06.3 lack https://github.com/ovn-org/ovn/commit/996ed75db776c59098b6539d0c03d43977202885 or more)

So, could I use ovs 2.13.4 in compile and use ovs 2.13.9 in install. I don't know if these incompatibilities are limited to compilation.

**Comment by numansiddique** [comment]
Yes you can.

**Comment by ExploreScience** [comment]
If I want to use ovs 2.16.1, which version of ovn should I use?

**Comment by dceara** [comment]
If you want to use ovs 2.16.1 for the dataplane (ovs-vswitchd/ovsdb-server) there should be no problem using any other supported OVN version.  For compile time dependency please use the OVS submodule version from the OVN release you're running.
