### ISSUE TITLE
Consider to support packets path probing?

### ISSUE THREAD

**Issue by gujun4990** [ovn-org/ovn#185]
I have checked the features of ovn and not found the feature that support packets path probing. I also search some relevant papers, such as the below papers:
- [SDN traceroute: Tracing SDN Forwarding without Changing Network Behavior](http://ericrozner.com/papers/sdn-traceroute-hotsdn-2014-final.pdf)
- [SDNProbe: Lightweight Fault Localization in the Error-Prone Environment](https://www.csie.ntu.edu.tw/~hchsiao/pub/2018_IEEE_ICDCS.pdf)
- [SDN Spotlight: A real-time OpenFlow troubleshooting framework](https://www.sciencedirect.com/science/article/pii/S0167739X22000899)

So I want to know whether we have a plan to develop the feature or tool that support packets path probing.

**Comment by dceara** [comment]
@gujun4990 one thing that might be interesting to check out is https://github.com/retis-org/retis

**Comment by gujun4990** [comment]
wow, thank you. I will prepare to investigate the project.

**Comment by gujun4990** [comment]
I have review the work about retis project. Nice to satisfy my requirements. I will continue to follow the project. Thanks again.
