### ISSUE TITLE
If the OpenStack I installed is ussuri, do I still need to install package python-networking-ovn?

### ISSUE THREAD

**Issue by ExploreScience** [ovn-org/ovn#187]
I want to integrate OpenStack with ovn. If the OpenStack I installed is ussuri, do I still need to install package python-networking-ovn? 
I can not find the python-netowrking-ovn.

**Comment by booxter** [comment]
1. This is a repo for OVN, not OpenStack OVN integration. A better venue for the question would be e.g. openstack-discuss mailing list.
2. Neutron / Ussuri has OVN ML2 driver integrated into the tree. No need for a separate package to install.
