### ISSUE TITLE
What ovn packages need to be installed when I install openstack in a common way？

### ISSUE THREAD

**Issue by ExploreScience** [ovn-org/ovn#188]
The ovn openstack tutorial on the ovn website installs OpenStack by installing DevStack. Now I install OpenStack in a normal way. What ovn packages do I need to install? My system is centos 8 and the installed OpenStack is Ussuri.

**Comment by booxter** [comment]
@ExploreScience please direct the question to a more appropriate venue. Depending on the installation method you use, it may be either RDO mailing list or openstack-discuss mailing list.

This github repo maintains OVN core components, not OpenStack or any of its installation mechanisms.

**Comment by ExploreScience** [comment]
Thans for your reply, I will look to openstack-discuss mailing list for answers.
