### ISSUE TITLE
How to implement many-to-many conversion when the nat type is snat

### ISSUE THREAD

**Issue by wanghuiheze** [ovn-org/ovn#189]
How to implement many-to-many conversion when the nat type is snat？

```
router fefe3e87-dc7f-4597-a1e7-f8a12158810a (gw)
    port lr-outside
        mac: "00:00:00:AA:BB:CC"
        networks: ["192.168.0.200/24"]
    port lr-gw
        mac: "00:00:00:00:00:11"
        networks: ["1.1.1.1/24"]
    nat 7674b614-8586-407d-998d-1345140c83f5
        external ip: "192.168.0.200"
        logical ip: "1.1.1.0/24"
        type: "snat"
```
I configured nat of type snat on the centralized gateway, external ip is "192.168.0.200",logical ip is cidr "1.1.1.0/24",But now I think external ip is cidr or Multiple IP.
I query ovs document openflow flow table is supported,How to configure it in ovn?

**Comment by dceara** [comment]
It's not supported to use CIDRs as external IPs for NATs in OVN.
