### ISSUE TITLE
is there a way to set switch lb vip in the same subnet as lb vip its backend ip

### ISSUE THREAD

**Issue by bobz965** [ovn-org/ovn#190]
``` bash

(vv) root@wk:~/dev/tests/kube-ovn/ovn-vip-slr# k ko nbctl show ovn-default
switch 887cf610-d30d-45e1-9b12-ae1369e0fd45 (ovn-default)
    port ovn-default-ovn-cluster
        type: router
        router-port: ovn-cluster-ovn-default
    port coredns-787d4945fb-55zgx.kube-system
        addresses: ["00:00:00:65:79:8D 10.16.0.5"]
    port ovn-default-vip
        type: virtual
        addresses: ["00:00:00:93:04:11 10.16.0.10"]



**(vv) root@wk:~/dev/tests/kube-ovn/ovn-vip-slr# k ko nbctl lb-list
UUID                                    LB                  PROTO      VIP                     IPs
4703a0a4-c4df-4f70-869b-8f63cf6f102f    cluster-tcp-sess    tcp        1.1.1.1:8888            10.16.0.8:80,10.16.0.9:80
                                                            tcp        10.16.0.10:8888         10.16.0.8:80,10.16.0.9:80
                                                            
                                                 

nginx-netshoot-64c44bfcf6-2qzwv:~# curl 10.16.0.10:8888
curl: (7) Failed to connect to 10.16.0.10 port 8888 after 3067 ms: Couldn't connect to server
nginx-netshoot-64c44bfcf6-2qzwv:~#
nginx-netshoot-64c44bfcf6-2qzwv:~#
nginx-netshoot-64c44bfcf6-2qzwv:~#
nginx-netshoot-64c44bfcf6-2qzwv:~#
nginx-netshoot-64c44bfcf6-2qzwv:~# curl 1.1.1.1:8888
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>



```

![image](https://github.com/ovn-org/ovn/assets/7981158/10bfae51-a3b2-4444-9b85-710836f9fd57)

as you can see, if i use the same subnet ip as vip, it will send arp first, whether the vip has logical switch port or not

and if i use the other subnet ip, it works well

**Comment by bobz965** [comment]
thanks, i made it

**Comment by bobz965** [comment]
hi @dceara ， after i use a lsp with it arp proxy enabled, and its mac is gw mac, the gw ip can not ping successfully, after i delete the lsp with gw mac and arp proxy enabled, then the gw ip can not ping successfully.

![image](https://github.com/ovn-org/ovn/assets/7981158/6d1a1f50-a3fb-43e2-9151-8e1218d0b631)

![image](https://github.com/ovn-org/ovn/assets/7981158/b9595894-873e-42b1-8d27-6db61b038783)



![image](https://github.com/ovn-org/ovn/assets/7981158/3ad7d84c-e31f-4173-b0f8-72c23bd2e1e4)

**Comment by bobz965** [comment]
arp works always well in this case, I think ICMP should work well too

**Comment by numansiddique** [comment]
Try the option (a) suggested by @dceara 

ovn-nbctl lr-lb-add <router> <lb>

This will work.

**Comment by bobz965** [comment]
> Try the option (a) suggested by @dceara
> 
> ovn-nbctl lr-lb-add
> 
> This will work.

Thanks for you reply @dceara, i will try apply a router lb as the switch lb. but i think the `arp proxy lsp` way is more simple and convenient.   create two lb `router and switch lb` looks too heavy。

**Comment by dceara** [comment]
@bobz965 You could try to restrict the proxy_arp cidr to just the list of VIPs you want the proxy ARP to apply to.

Something like here: https://github.com/ovn-org/ovn/blob/4a1ca1e658f92ddfbd282d5a1bbf2affdb5e7f31/tests/system-ovn.at#LL10550C1-L10550C160
