### ISSUE TITLE
In which version dvr of fip port forwarding is implemented

### ISSUE THREAD

**Issue by HanGuangyu** [ovn-org/ovn#193]
hello, I used kolla-ansible to deploy openstack yoga and victoria with ovn banckend. And I create floating ip port forwarding. But I found that, in yoga, the  port forwarding traffic flows directly from compute nodes.  In victoria, the  port forwarding traffic still goes through network nodes

I would like to ask, is this related to the neutron version, or is it caused by a different ovn version?

the ovn version in yoga is 22.06.1, and the ovn version in Victoria is 20.03.2

**Comment by dceara** [comment]
I think this is related to how OVN is deployed so it's probably best to discuss with the [kolla-ansible folks](https://github.com/openstack/kolla-ansible#getting-involved)
