### ISSUE TITLE
Support for GTP tunnels

### ISSUE THREAD

**Issue by rrosa-cn** [ovn-org/ovn#195]
Hello,

OVS itself does support [GTP](https://docs.openvswitch.org/en/latest/faq/configuration/#:~:text=A%3A%20Yes.%20Starting%20with%20version%202.13%2C%20the%20Open%20vSwitch%20userspace%20datapath%20supports%20GTP%2DU%20(GPRS%20Tunnelling%20Protocol%20User%20Plane%20(GTPv1%2DU)).%20TEID%20is%20set%20by%20using%20tunnel%20key%20field.) but I couldn't find any information on whether OVN does too. Is it possible to create a network topology with OVN which supports GTP tunnels and is it possible to create the tunnels from the OVN level?

**Comment by dceara** [comment]
@rrosa-cn sorry for the delay in replying.  OVN doesn't support GTP tunnels.  I'm not aware of any plans for supporting them but if you have a use case we can discuss it on the dev mailing list:

ovs-dev@openvswitch.org

Thanks,
Dumitru
