### ISSUE TITLE
can not delete Load_Balancer_Health_Check by its uuid

### ISSUE THREAD

**Issue by bobz965** [ovn-org/ovn#201]
![image](https://github.com/ovn-org/ovn/assets/7981158/8943f1fc-b802-4472-9ee2-455ab5954089)

``` bash


root@empty:~/test/kube-ovn/lb-to-subnet# kubectl ko nbctl --version
ovn-nbctl 22.12.1
Open vSwitch Library 3.1.3
DB Schema 7.0.0
root@empty:~/test/kube-ovn/lb-to-subnet#

```

**Comment by numansiddique** [comment]
Load_Balancer_Health_Check is a non root table which means you can't delete the row.
Instead you need to remove this health check from the load balancer referencing it.

Like.

ovn-nbctl remove load_balancer <load_balancer_uuid> health_checks 8ba16c17-.....

Hope this helps.

**Comment by numansiddique** [comment]
It is not an issue. So closing it.

**Comment by bobz965** [comment]
> Load_Balancer_Health_Check is a non root table which means you can't delete the row. Instead you need to remove this health check from the load balancer referencing it.
> 
> Like.
> 
> ovn-nbctl remove load_balancer <load_balancer_uuid> health_check 8ba16c17-.....
> 
> Hope this helps.

Thanks
