### ISSUE TITLE
how to decide the ovn sb nb comact interval when in a big cluster

### ISSUE THREAD

**Issue by bobz965** [ovn-org/ovn#206]
I have a cluster that may have a 10k-20k logical switch port, I want to know how to calculate the better interval to do nb and sb compact operation.

**Comment by dceara** [comment]
Compaction intervals are not configurable AFAIK.  CC: @igsilya

**Comment by igsilya** [comment]
Interval for automatic compaction is not configurable, but it can be invoked manually.  However, I'd recommend to not use manual compaction unless you're debugging something.

**Comment by bobz965** [comment]
Thanks
