### ISSUE TITLE
missing ovn-sim or something to allow helper commands in ovn sandbox

### ISSUE THREAD

**Issue by flavio-fernandes** [ovn-org/ovn#21]
Prior to split, I could do commands from ovs-sim as shown below [1].

Trouble is that now ovs-sim no longer has ovn related functions such as `ovn-nbctl`
and there is no ovs-sim (nor ovn-sim) in ovg-org/ovn. I wonder if we could re-instate
ovs-sim inside ovn repo, or have a way of importing helper functions in ovn sandbox,
such as `net_add` and `as`.

Ref commit https://github.com/openvswitch/ovs/commit/f3e24610ea18eb873dc860f1710432e9aacd27fd that removes ovn related
helpers from utilities/ovs-sim (for the right reasons!)

Also, I see that there are some left over ovs-sim "stuff" in ovn-org/ovn, so it was not
completely expunged:
```
$ grep -ilr 'ovs-sim' *
Documentation/automake.mk
Documentation/ref/index.rst
Documentation/ref/ovs-sim.1.rst
Documentation/conf.py
NEWS
``` 

[1]: https://gist.githubusercontent.com/anonymous/08f3d07aff4a26e368da3e5e12c7e3a1/raw/386f48218221b8a1ba2a70642c2204e540133937/gistify194222.txt

```
[1]

cd ./utilities && rm -rf ./sandbox && ./ovs-sim

ovn_start

# Create a bridge do simulate connection between hypervisors
net_add n1
for i in 1 2; do
    sim_add hv$i
    as hv$i
    ovs-vsctl add-br br-phys
    ovn_attach n1 br-phys 192.168.0.$i
done

# Add port inside hv1's context
as hv1
ovs-vsctl -- add-port br-int hv1-vif1 -- \
    set interface hv1-vif1 mac="00\:11\:22\:33\:44\:55" \
    external-ids:iface-id=foo ofport-request=1
fooMac=$(ovs-ofctl show br-int | grep -E hv.-vif1 | grep -oP "(?<=addr:).*")

# Add port inside hv2's context
as hv2
ovs-vsctl -- add-port br-int hv2-vif1 -- \
    set interface hv2-vif1 external-ids:iface-id=bar ofport-request=1
barMac=$(ovs-ofctl show br-int | grep -E hv.-vif1 | grep -oP "(?<=addr:).*")

ovn-nbctl ls-add sw0
ovn-nbctl lsp-add sw0 foo
ovn-nbctl lsp-add sw0 bar
ovn-nbctl lsp-set-addresses foo $fooMac
ovn-nbctl lsp-set-addresses bar $barMac
```

**Comment by putnopvut** [comment]
I wonder if it would be possible to create an ovn-sim script in the OVN repo that exports the proper OVN functions (ovn_start, ovn_attach, etc.), adds local directories to the $PATH, and then calls ovs-sim directly. I think it might work. By doing that, you'd have the same environment on startup that you do with ovs-sim, plus the ability to call ovn-specific functions.

How does this sound?

**Comment by flavio-fernandes** [comment]
> I wonder if it would be possible to create an ovn-sim script in the OVN repo that exports the proper OVN functions (ovn_start, ovn_attach, etc.), adds local directories to the $PATH, and then calls ovs-sim directly. I think it might work. By doing that, you'd have the same environment on startup that you do with ovs-sim, plus the ability to call ovn-specific functions.
> 
> How does this sound?

sounds awesome! I love the idea of using ovs primitives from ovs to avoid duplication
