### ISSUE TITLE
OVSDB-server of SBDB cluster node takes 100% CPU

### ISSUE THREAD

**Issue by GeorgeShagovCloud** [ovn-org/ovn#223]
Hello Team!
 
OVS-2.17.7
OVN-22.03.3
 
We have a cluster of SDBD in 5 Nodes. When we make a load from NBDB/NorthD (making/deleting routers) we observe a strange behavior:
Some nodes (ovsdb-server) of the cluster spontaneously starts in 100% CPU
It could be one or two nodes, not leading, what is remarkable
Leading node and the rest nodes of the cluster remains in 20-30% CPU or even less
This happens for 3-10 mins
Usually, it is causing leader re-election
We have extended election-time for a leader re-election it gets better; re-election is not so frequent; ant yet we are still observing 100% for some node
 
Here are the very confusing lines from the logs for the nodes (ovsdb-server) with 100% CPU utilization:
 
2023-11-04T07:01:13.447Z|292408|poll_loop|INFO|wakeup due to 1-ms timeout at ../lib/reconnect.c:677 (72% CPU usage)
2023-11-04T07:01:13.448Z|292409|poll_loop|INFO|wakeup due to 1-ms timeout at ../lib/reconnect.c:677 (72% CPU usage)
 
Any clues are extremely appreciated!
 
Thnx in advance
Yours truly, George

**Comment by GeorgeShagovCloud** [comment]
Hello Team!

Update

We have extended logs to DBG level at the problem SBDB Node and it was found that there is a very Excessive monitor_cond_change request from ovn_controller of one of Network Nodes.
This request takes about 230Kb in Json. It has about 3k+ datapathes. But the uniq datapathes are about half of these, i.e. 1500+
It this a normal behavior I wonder? Or it looks like a bug?

Thnx in advance

**Comment by GeorgeShagovCloud** [comment]
Resolved by this hint: https://mail.openvswitch.org/pipermail/ovs-discuss/2023-November/052802.html

Strong Suggestion to OVN Team: change the default value of `external_ids:ovn-monitor-all ` from false to true

**Comment by dceara** [comment]
Unfortunately we cannot change defaults like that.  We have to keep `ovn-monitor-all` false by default to not affect users that didn't enable it before.  One visible change might be sudden memory usage increase for ovn-controllers.

The CMS already configures various other ovn-controller knobs in the local OVSDB, it could also explicitly set `ovn-monitor-all=true` if that's the desired way of monitoring.
