### ISSUE TITLE
Does OVN support DPDK?

### ISSUE THREAD

**Issue by JohnHaan** [ovn-org/ovn#53]
In case of br-int has dpdk interfaces below:
```
    Bridge br-int
        fail_mode: secure
        datapath_type: netdev
        Port tunbond
            Interface tun0
                type: dpdk
                options: {dpdk-devargs="0000:1a:00.1", n_rxq="2"}
            Interface tun1
                type: dpdk
                options: {dpdk-devargs="0000:d8:00.1", n_rxq="2"}
        Port br-int
            Interface br-int
                type: internal
```

We need to configure to `ovn-encap-ip` in the external-ids option

```
ovs-vsctl set open . external-ids:ovn-encap-ip={IP ADDRESS}
```

However, the dpdk interface does not have an ip adress.

Is there any other command for configure overlay?

**Comment by numansiddique** [comment]
Since OVN is one layer above OVS, It should be transparent to OVN.
I think OVN does support DPDK.

I don't think there is any other way. ovn-controller expects external_ids:ovn-encap-ip to be configured.

**Comment by numansiddique** [comment]
Closing this issue. Please reopen if something needs to be done in OVN.

Thanks
