### ISSUE TITLE
Does OVN support networking_sfc?

### ISSUE THREAD

**Issue by ruoniao** [ovn-org/ovn#56]
Does ovn have any driver for networking_sfc of openstack neutron?

**Comment by numansiddique** [comment]
@danalsan Do you have any comments here ?

From what I know, it doesn't. 

Thanks
Numan

**Comment by danalsan** [comment]
> @danalsan Do you have any comments here ?
> 
> From what I know, it doesn't.
> 

There is a spec [0] that was approved back in the queens cycle but I don't think it was ever implemented.

[0] https://docs.openstack.org/networking-sfc/latest/contributor/sfc_ovn_driver.html

**Comment by russellb** [comment]
Right, it was not done.  It depends on changes to core OVN which were not completed and merged.

**Comment by ruoniao** [comment]
@russellb Is this feature in the planning list ？

**Comment by russellb** [comment]
I'm not aware of anyone working on it.
