### ISSUE TITLE
ovn qos only half of setting

### ISSUE THREAD

**Issue by suichangyin** [ovn-org/ovn#62]
environment：
\# uname -a
Linux node101 4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
\# ovn-nbctl --version
ovn-nbctl 20.03.0
Open vSwitch Library 2.13.90
DB Schema 5.22.0

I set the qos of two port:
  table=8 (ls_in_qos_meter    ), priority=2002 , match=(inport == "23145b86-f915-48aa-952c-e757bae327da"), action=(set_meter(10000); next;)
  table=8 (ls_in_qos_meter    ), priority=2002 , match=(inport == "31a72696-47fd-4e6a-91ad-1d0a91d7449e"), action=(set_meter(10000); next;)
  table=8 (ls_in_qos_meter    ), priority=0    , match=(1), action=(next;)
  table=5 (ls_out_qos_mark    ), priority=0    , match=(1), action=(next;)
  table=6 (ls_out_qos_meter   ), priority=2002 , match=(outport == "23145b86-f915-48aa-952c-e757bae327da"), action=(set_meter(10000); next;)
  table=6 (ls_out_qos_meter   ), priority=2002 , match=(outport == "31a72696-47fd-4e6a-91ad-1d0a91d7449e"), action=(set_meter(10000); next;)

And i test the network by iperf.
it show only half of setting limit. i set 10000,iperf show only 5M/s

if the qos only set to one port, the result is correct.

has anyone encountered this problem？

**Comment by numansiddique** [comment]
I guess you're hitting an issue which was fixed by this commit - d409c8b8ea587886f391af14c2c32d3428e4fc55

Is it possible for you to try with OVN 20.09 or master and see if the issue still persists ?


@LorenzoBianconi Do you think suichangyin is hitting the same issue you fixed ?

Thanks
Numan

**Comment by suichangyin** [comment]
> I guess you're hitting an issue which was fixed by this commit - [d409c8b](https://github.com/ovn-org/ovn/commit/d409c8b8ea587886f391af14c2c32d3428e4fc55)
> 
> Is it possible for you to try with OVN 20.09 or master and see if the issue still persists ?
> 
> @LorenzoBianconi Do you think suichangyin is hitting the same issue you fixed ?
> 
> Thanks
> Numan

Thanks...I test the 20.09, and it work fine。
ovn-nbctl 20.09.0
Open vSwitch Library 2.14.0
DB Schema 5.27.0

**Comment by numansiddique** [comment]
Great. Thanks for the confirmation.
