### ISSUE TITLE
IGMP snooping fails when running OVN with RBAC

### ISSUE THREAD

**Issue by phvalguima** [ovn-org/ovn#77]
I am running OpenStack Ussuri on top of Ubuntu Bionic with OVN 20.03.
Also verified this issue with 20.06.

When enabling IGMP snooping as described on OpenStack documentation:
https://docs.openstack.org/neutron/latest/admin/ovn/igmp.html

As VMs submit join requests, IGMP_Group table is not getting populated.

On ovn-controller logs, I can see the following error:
2021-02-06T17:17:40.916Z|00028|ovsdb_idl|WARN|transaction error: {"details":"RBAC rules for client \"REDACTED\" role \"ovn-controller\" prohibit row insertion into table \"IGMP_Group\".","error":"permission error"}

Indeed, checking ovn-architecture document:
https://github.com/ovn-org/ovn/blob/master/ovn-architecture.7.xml#L2530

And it says RBAC_Permission is hard-coded to the values above. There is no entry for IGMP_Group.
We should extend RBAC_Permission to IGMP_Group table with rights to insert and delete for ovn-controller units.

**Comment by dceara** [comment]
@phvalguima Thanks reporting the issue!

I posted a patch to fix it:
https://mail.openvswitch.org/pipermail/ovs-dev/2021-February/380160.html

**Comment by phvalguima** [comment]
Hi @dceara,

Thanks for taking your time and fixing it.
I had exactly the same patch on my own fork: https://github.com/phvalguima/ovn/tree/rbac-igmp-group-coverage
It worked fine and fixed the issue on my tests.

Another question I have is: once I enable IGMP snooping on OVN, IGMP traffic stops getting routed to the external networks. That means, any IGMP router on my external networks will be unaware a given VM wants to access a group.

On OVS, there is one way to set this correctly once IGMP snooping is enabled:

ovs-vsctl   set   Port  <PORT_NAME>  other_config:mcast-snooping-flood-reports=true

That ensures IGMP control messages won't be trapped within OVS and hit the external networks.
How can that work within OVN? I see that IGMP traffic is trapped by an OpenFlow setting, so I am not sure the configuration above will work as well.

**Comment by dceara** [comment]
> Hi @dceara,
> 
> Thanks for taking your time and fixing it.
> I had exactly the same patch on my own fork: https://github.com/phvalguima/ovn/tree/rbac-igmp-group-coverage

@phvalguima Oh, sorry about that, I didn't realize you were working on it already.  Please post the patch to the mailing list and I'll retract mine. Posting guidelines are here:
https://github.com/ovn-org/ovn/blob/master/Documentation/internals/contributing/submitting-patches.rst

> It worked fine and fixed the issue on my tests.
> 
> Another question I have is: once I enable IGMP snooping on OVN, IGMP traffic stops getting routed to the external networks. That means, any IGMP router on my external networks will be unaware a given VM wants to access a group.
> 
> On OVS, there is one way to set this correctly once IGMP snooping is enabled:
> 
> ovs-vsctl set Port <PORT_NAME> other_config:mcast-snooping-flood-reports=true

You can enable something similar in OVN too with:
```
ovn-nbctl set Logical_Switch_Port <port-name> options:mcast_flood_reports='true'
```
Please let me know if that works for you.

> 
> That ensures IGMP control messages won't be trapped within OVS and hit the external networks.
> How can that work within OVN? I see that IGMP traffic is trapped by an OpenFlow setting, so I am not sure the configuration above will work as well.

Thanks,
Dumitru

**Comment by numansiddique** [comment]
@phvalguima  You can also do a PR if for some reason you cannot send the patch to the ovs-dev mailing list.

**Comment by phvalguima** [comment]
@numansiddique @dceara thanks for the tips and patience
I've submitted it via e-mail.

**Comment by phvalguima** [comment]
@dceara I believe we can close this issue
