### ISSUE TITLE
In the ovn21.03 version, bfd does not work properly

### ISSUE THREAD

**Issue by zhanrox2** [ovn-org/ovn#84]
Verified on version:

- OVN：21.03
- OVS：2.15.90
- OS：Red Hat Enterprise Linux Server release 7.6 (Maipo)
- Kernel：4.19.8-1.el7.elrepo.x86_64

Today, I want to verify the effectiveness of monitoring static routing based on the BFD protocol, but bfd does not work properly.
The problem reproduces as follows：

	# ovn-nbctl lr-add r1
	# ovn-nbctl lrp-add r1 r1-sw1 00:00:c0:a8:01:fe 192.168.1.254/24
	
	# ovn-nbctl ls-add sw1
	# ovn-nbctl lsp-add sw1 port1
	# ovn-nbctl lsp-set-addresses port1 "00:00:c0:a8:01:01 192.168.1.1"
	# ovn-nbctl lsp-add sw1 port2
	# ovn-nbctl lsp-set-addresses port2 "00:00:c0:a8:01:02 192.168.1.2"
	# ovn-nbctl lsp-add sw1 sw1-r1
	# ovn-nbctl lsp-set-type sw1-r1 router
	# ovn-nbctl lsp-set-addresses sw1-r1 00:00:c0:a8:01:fe
	# ovn-nbctl lsp-set-options sw1-r1 router-port=r1-sw1
	
	# ip netns add c01
	# ip link add veth0 type veth peer name veth1
	# ip link set veth1 netns c01
	# ip netns exec c01 ip link set lo up
	# ip netns exec c01 ip link set veth1 up
	# ip netns exec c01 ip link set veth1 address 00:00:c0:a8:01:01
	# ip netns exec c01 ip addr add 192.168.1.1/24 dev veth1
	# ip netns exec c01 ip route add default via 192.168.1.254
	# ip link set veth0 up
	# ovs-vsctl add-port br-int veth0
	# ovs-vsctl set Interface veth0 external_ids:iface-id=port1
	
	# ovn-nbctl create bfd logical_port=r1-sw1 dst_ip=192.168.1.1 min_tx=1000 min_rx=1000 detect_mult=3
	2d1cc34e-9de4-4765-a121-b45b3f3deb31
	# ovn-nbctl --may-exist --policy=dst-ip  --bfd=2d1cc34e-9de4-4765-a121-b45b3f3deb31 lr-route-add r1 172.245.0.0/16 192.168.1.1 r1-sw1

	# ip netns exec c01 bash
	# bfdd-beacon --listen=0.0.0.0
	# bfdd-control session new set mintx 1 s
	# bfdd-control session new set minrx 1 s
	# bfdd-control session new set multi 3
	# bfdd-control connect local 192.168.1.1 remote 192.168.1.254
	# exit

	# ovn-nbctl list bfd
	_uuid               : 2d1cc34e-9de4-4765-a121-b45b3f3deb31
	detect_mult         : []
	dst_ip              : "192.168.1.1"
	external_ids        : {}
	logical_port        : r1-sw1
	min_rx              : []
	min_tx              : []
	options             : {}
	status              : down
	
	# ovn-nbctl list logical_router_static_route
	_uuid               : b0c29507-dc56-4ad6-b60f-8f93823b9903
	bfd                 : 2d1cc34e-9de4-4765-a121-b45b3f3deb31
	external_ids        : {}
	ip_prefix           : "172.245.0.0/16"
	nexthop             : "192.168.1.1"
	options             : {}
	output_port         : r1-sw1
	policy              : dst-ip

It can be found that the status in the ovn bfd table is always down。

In addition, I caught the packet in c01 and found that there was no bdf packet that was returned from ovn：

	# ip netns exec c01 bash
	# tcpdump -eni veth1 -vvv
	tcpdump: listening on veth1, link-type EN10MB (Ethernet), capture size 262144 bytes
	23:08:12.007600 00:00:c0:a8:01:01 > 00:00:c0:a8:01:fe, ethertype IPv4 (0x0800), length 66: (tos 0x0, ttl 255, id 43241, offset 0, flags [DF], proto UDP (17), length 52)
		192.168.1.1.51838 > 192.168.1.254.bfd-control: [bad udp cksum 0x8481 -> 0xdd9c!] BFDv1, length: 24
		Control, State Down, Flags: [none], Diagnostic: No Diagnostic (0x00)
		Detection Timer Multiplier: 3 (3000 ms Detection time), BFD Length: 24
		My Discriminator: 0x63a1b8e2, Your Discriminator: 0x00000000
		Desired min Tx Interval:    1000 ms
		Required min Rx Interval:   1000 ms
		Required min Echo Interval:    0 ms
	23:08:12.811107 00:00:c0:a8:01:01 > 00:00:c0:a8:01:fe, ethertype IPv4 (0x0800), length 66: (tos 0x0, ttl 255, id 43452, offset 0, flags [DF], proto UDP (17), length 52)
		192.168.1.1.51838 > 192.168.1.254.bfd-control: [bad udp cksum 0x8481 -> 0xdd9c!] BFDv1, length: 24
		Control, State Down, Flags: [none], Diagnostic: No Diagnostic (0x00)
		Detection Timer Multiplier: 3 (3000 ms Detection time), BFD Length: 24
		My Discriminator: 0x63a1b8e2, Your Discriminator: 0x00000000
		Desired min Tx Interval:    1000 ms
		Required min Rx Interval:   1000 ms
		Required min Echo Interval:    0 ms
	23:08:13.694942 00:00:c0:a8:01:01 > 00:00:c0:a8:01:fe, ethertype IPv4 (0x0800), length 66: (tos 0x0, ttl 255, id 43942, offset 0, flags [DF], proto UDP (17), length 52)
		192.168.1.1.51838 > 192.168.1.254.bfd-control: [bad udp cksum 0x8481 -> 0xdd9c!] BFDv1, length: 24
		Control, State Down, Flags: [none], Diagnostic: No Diagnostic (0x00)
		Detection Timer Multiplier: 3 (3000 ms Detection time), BFD Length: 24
		My Discriminator: 0x63a1b8e2, Your Discriminator: 0x00000000
		Desired min Tx Interval:    1000 ms
		Required min Rx Interval:   1000 ms
		Required min Echo Interval:    0 ms

The following is a logical flow table that simulates c01 sending bdf packages to ovn

	# ovn-trace --detailed sw1 'inport == "port1" && eth.src == 00:00:c0:a8:01:01 && ip4.src == 192.168.1.1 && eth.dst == 00:00:c0:a8:01:fe && ip4.dst == 192.168.1.254 && udp.dst == 3784'
	# udp,reg14=0x1,vlan_tci=0x0000,dl_src=00:00:c0:a8:01:01,dl_dst=00:00:c0:a8:01:fe,nw_src=192.168.1.1,nw_dst=192.168.1.254,nw_tos=0,nw_ecn=0,nw_ttl=0,tp_src=0,tp_dst=3784
	
	ingress(dp="sw1", inport="port1")
	---------------------------------
	0. ls_in_port_sec_l2 (ovn-northd.c:4793): inport == "port1", priority 50, uuid c40caf3c
		next;
	23. ls_in_l2_lkup (ovn-northd.c:7385): eth.dst == 00:00:c0:a8:01:fe, priority 50, uuid 2ccc3979
		outport = "sw1-r1";
		output;
	
	egress(dp="sw1", inport="port1", outport="sw1-r1")
	--------------------------------------------------
	0. ls_out_pre_lb (ovn-northd.c:4939): ip && outport == "sw1-r1", priority 110, uuid f4ea2f47
		next;
	10. ls_out_port_sec_l2 (ovn-northd.c:4888): outport == "sw1-r1", priority 50, uuid 954503a0
		output;
		/* output to "sw1-r1", type "patch" */
	
	ingress(dp="r1", inport="r1-sw1")
	---------------------------------
	0. lr_in_admission (ovn-northd.c:9326): eth.dst == 00:00:c0:a8:01:fe && inport == "r1-sw1", priority 50, uuid 387d8d1d
		xreg0[0..47] = 00:00:c0:a8:01:fe;
		next;
	1. lr_in_lookup_neighbor (ovn-northd.c:9405): 1, priority 0, uuid dd08c88e
		reg9[2] = 1;
		next;
	2. lr_in_learn_neighbor (ovn-northd.c:9414): reg9[2] == 1, priority 100, uuid de366c4f
		next;
	3. lr_in_ip_input (ovn-northd.c:9239): ip4.dst == 192.168.1.254 && udp.dst == 3784, priority 110, uuid 0e297771
		handle_bfd_msg();

Can anyone tell me where the problem is, is my usage incorrect? @blp @dceara @numansiddique

**Comment by LorenzoBianconi** [comment]
@zhanrox2: ovn bfd implementation relies on gw routers or gw router ports, the port where bfd is running can't be distributed and must run on given hv. Can you please try running bfd on a gw router port?

**Comment by zhanrox2** [comment]
@LorenzoBianconi Thanks，we verified that it is indeed as you said
