### ISSUE TITLE
Make ddlog-dev branch read-only

### ISSUE THREAD

**Issue by ryzhyk** [ovn-org/ovn#9]
I would like to keep this branch around for now, as it passes all tests (unlike `ddlog-dev-v2`) but mark it read-only, to make sure that all future PR's are submitted against `ddlog-dev-v2`.

If this sounds like a good plan, could someone with admin permissions apply this restriction?

**Comment by numansiddique** [comment]
I have added a branch protection rule for the branch - ddlog-dev.

**Comment by blp** [comment]
> I have added a branch protection rule for the branch - ddlog-dev.

I didn't even know Github had those! Good to know.
